// <auto-generated />
using System;
using Ex4_Pizzaria;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ex4_Pizzaria.Migrations
{
    [DbContext(typeof(Pizzaria09Context))]
    partial class Pizzaria09ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ex4_Pizzaria.Models.Borda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_Borda");

                    b.ToTable("Borda", (string)null);
                });

            modelBuilder.Entity("Ex4_Pizzaria.Models.Massa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_Massa");

                    b.ToTable("Massa", (string)null);
                });

            modelBuilder.Entity("Ex4_Pizzaria.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IdPizza")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Pizza_Id");

                    b.Property<string>("IdStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Status_Id");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Pedido");

                    b.HasIndex("StatusId");

                    b.ToTable("Pedido", (string)null);
                });

            modelBuilder.Entity("Ex4_Pizzaria.Models.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IdBordas")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Sabores_Id");

                    b.Property<string>("IdMassa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Pizza_Id");

                    b.HasKey("Id")
                        .HasName("PK_Pizza");

                    b.ToTable("Pizza", (string)null);
                });

            modelBuilder.Entity("Ex4_Pizzaria.Models.Pizza_Sabores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IdPizza")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdSabores")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_PizzaSabor");

                    b.ToTable("Pizza_Sabores", (string)null);
                });

            modelBuilder.Entity("Ex4_Pizzaria.Models.Sabor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_Sabores");

                    b.ToTable("Sabores", (string)null);
                });

            modelBuilder.Entity("Ex4_Pizzaria.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomeStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_Status");

                    b.ToTable("Status", (string)null);
                });

            modelBuilder.Entity("Ex4_Pizzaria.Models.Pedido", b =>
                {
                    b.HasOne("Ex4_Pizzaria.Models.Status", null)
                        .WithMany("Pedidos")
                        .HasForeignKey("StatusId");
                });

            modelBuilder.Entity("Ex4_Pizzaria.Models.Status", b =>
                {
                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
